
#this file run with "condor_submit runparallel.sub" for GPU LAB job
## directories log, error, and output must exist
universe = vanilla
log    =    log/job1-chtc_$(Cluster)_$(Process).log
error  =  error/job1-chtc_$(Cluster)_$(Process).err
output = output/job1_$(Cluster)_$(Process).out

executable = ./run.sh

arguments = $(json_file)  >> test1128001.out &

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files =  modules.py, network_lba.py, lba_11gpu.json,lba_12gpu.json,input_files.txt,  http://proxy.chtc.wisc.edu/SQUID/chtc/python38.tar.gz, packages.tar.gz
##Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true)

+WantGPULab = true
+GPUJobLength = "short"
+wantFlocking = true

request_gpus = 1
request_cpus = 1
request_memory = 48GB
request_disk = 32GB

queue json_file from input_files.txt
