library(ape)
library(phangorn)
## read true trees
d = read.table("labels372783-0.1-40.0-1.0.in", header=FALSE)
n = length(d$V1)
## labels from the simulating script:
quartets = c("((1,2),(3,4));", "((1,3),(2,4));", "((1,4),(2,3));")

args <- commandArgs(trailingOnly = F)
process <- args[8]
intprocess <- strtoi(process)
minus<-10*intprocess
print(minus)
#output file name
outname = paste("out",process,".csv",sep="")
#1-5 comparison
truetree0 = read.tree(text=quartets[d[n-minus,]])
print(quartets[d[n-minus,]])
njtree0 = read.tree(file="nj-tree0.txt")
mltree0 = read.tree(file="T30.raxml.bestTree")
bitree0 = read.nexus(file="test0-mb.nexus.con.tre")
## Calculating the Robinson-Foulds distance with true tree:
njdist0 = RF.dist(truetree0,njtree0, rooted=FALSE)
mldist0 = RF.dist(truetree0,mltree0, rooted=FALSE)
bidist0 = RF.dist(truetree0,bitree0, rooted=FALSE)
write.table(njdist0,file=outname,append = T,sep=',',row.names="njdist",col.names=F)
write.table(mldist0,file=outname,append = T,sep=',',row.names="mldist",col.names=F)
write.table(bidist0,file=outname,append = T,sep=',',row.names="bidist",col.names=F)

truetree1 = read.tree(text=quartets[d[n-1-minus,]])
print(quartets[d[n-1-minus,]])
njtree1 = read.tree(file="nj-tree1.txt")
mltree1 = read.tree(file="T31.raxml.bestTree")
bitree1 = read.nexus(file="test1-mb.nexus.con.tre")
## Calculating the Robinson-Foulds distance with true tree:
njdist1 = RF.dist(truetree1,njtree1, rooted=FALSE)
mldist1 = RF.dist(truetree1,mltree1, rooted=FALSE)
bidist1 = RF.dist(truetree1,bitree1, rooted=FALSE)
write.table(njdist1,file=outname,append = T,sep=',',row.names="njdist",col.names=F)
write.table(mldist1,file=outname,append = T,sep=',',row.names="mldist",col.names=F)
write.table(bidist1,file=outname,append = T,sep=',',row.names="bidist",col.names=F)

truetree2 = read.tree(text=quartets[d[n-2-minus,]])
print(quartets[d[n-2-minus,]])
njtree2 = read.tree(file="nj-tree2.txt")
mltree2 = read.tree(file="T32.raxml.bestTree")
bitree2 = read.nexus(file="test2-mb.nexus.con.tre")
## Calculating the Robinson-Foulds distance with true tree:
njdist2 = RF.dist(truetree2,njtree2, rooted=FALSE)
mldist2 = RF.dist(truetree2,mltree2, rooted=FALSE)
bidist2 = RF.dist(truetree2,bitree2, rooted=FALSE)
write.table(njdist2,file=outname,append = T,sep=',',row.names="njdist",col.names=F)
write.table(mldist2,file=outname,append = T,sep=',',row.names="mldist",col.names=F)
write.table(bidist2,file=outname,append = T,sep=',',row.names="bidist",col.names=F)

truetree3 = read.tree(text=quartets[d[n-3-minus,]])
print(quartets[d[n-3-minus,]])
njtree3 = read.tree(file="nj-tree3.txt")
mltree3 = read.tree(file="T33.raxml.bestTree")
bitree3 = read.nexus(file="test3-mb.nexus.con.tre")
## Calculating the Robinson-Foulds distance with true tree:
njdist3 = RF.dist(truetree3,njtree3, rooted=FALSE)
mldist3 = RF.dist(truetree3,mltree3, rooted=FALSE)
bidist3 = RF.dist(truetree3,bitree3, rooted=FALSE)
write.table(njdist3,file=outname,append = T,sep=',',row.names="njdist",col.names=F)
write.table(mldist3,file=outname,append = T,sep=',',row.names="mldist",col.names=F)
write.table(bidist3,file=outname,append = T,sep=',',row.names="bidist",col.names=F)

truetree4 = read.tree(text=quartets[d[n-4-minus,]])
print(quartets[d[n-4-minus,]])
njtree4 = read.tree(file="nj-tree4.txt")
mltree4 = read.tree(file="T34.raxml.bestTree")
bitree4 = read.nexus(file="test4-mb.nexus.con.tre")
## Calculating the Robinson-Foulds distance with true tree:
njdist4 = RF.dist(truetree4,njtree4, rooted=FALSE)
mldist4 = RF.dist(truetree4,mltree4, rooted=FALSE)
bidist4 = RF.dist(truetree4,bitree4, rooted=FALSE)
write.table(njdist4,file=outname,append = T,sep=',',row.names="njdist",col.names=F)
write.table(mldist4,file=outname,append = T,sep=',',row.names="mldist",col.names=F)
write.table(bidist4,file=outname,append = T,sep=',',row.names="bidist",col.names=F)

truetree5 = read.tree(text=quartets[d[n-5-minus,]])
print(quartets[d[n-5-minus,]])
njtree5 = read.tree(file="nj-tree5.txt")
mltree5 = read.tree(file="T35.raxml.bestTree")
bitree5 = read.nexus(file="test5-mb.nexus.con.tre")
## Calculating the Robinson-Foulds distance with true tree:
njdist5 = RF.dist(truetree5,njtree5, rooted=FALSE)
mldist5 = RF.dist(truetree5,mltree5, rooted=FALSE)
bidist5 = RF.dist(truetree5,bitree5, rooted=FALSE)
write.table(njdist5,file=outname,append = T,sep=',',row.names="njdist",col.names=F)
write.table(mldist5,file=outname,append = T,sep=',',row.names="mldist",col.names=F)
write.table(bidist5,file=outname,append = T,sep=',',row.names="bidist",col.names=F)

truetree6 = read.tree(text=quartets[d[n-6-minus,]])
print(quartets[d[n-6-minus,]])
njtree6 = read.tree(file="nj-tree6.txt")
mltree6 = read.tree(file="T36.raxml.bestTree")
bitree6 = read.nexus(file="test6-mb.nexus.con.tre")
## Calculating the Robinson-Foulds distance with true tree:
njdist6 = RF.dist(truetree6,njtree6, rooted=FALSE)
mldist6 = RF.dist(truetree6,mltree6, rooted=FALSE)
bidist6 = RF.dist(truetree6,bitree6, rooted=FALSE)
write.table(njdist6,file=outname,append = T,sep=',',row.names="njdist",col.names=F)
write.table(mldist6,file=outname,append = T,sep=',',row.names="mldist",col.names=F)
write.table(bidist6,file=outname,append = T,sep=',',row.names="bidist",col.names=F)

truetree7 = read.tree(text=quartets[d[n-7-minus,]])
print(quartets[d[n-7-minus,]])
njtree7 = read.tree(file="nj-tree7.txt")
mltree7 = read.tree(file="T37.raxml.bestTree")
bitree7 = read.nexus(file="test7-mb.nexus.con.tre")
## Calculating the Robinson-Foulds distance with true tree:
njdist7 = RF.dist(truetree7,njtree7, rooted=FALSE)
mldist7 = RF.dist(truetree7,mltree7, rooted=FALSE)
bidist7 = RF.dist(truetree7,bitree7, rooted=FALSE)
write.table(njdist7,file=outname,append = T,sep=',',row.names="njdist",col.names=F)
write.table(mldist7,file=outname,append = T,sep=',',row.names="mldist",col.names=F)
write.table(bidist7,file=outname,append = T,sep=',',row.names="bidist",col.names=F)

truetree8 = read.tree(text=quartets[d[n-8-minus,]])
print(quartets[d[n-8-minus,]])
njtree8 = read.tree(file="nj-tree8.txt")
mltree8 = read.tree(file="T38.raxml.bestTree")
bitree8 = read.nexus(file="test8-mb.nexus.con.tre")
## Calculating the Robinson-Foulds distance with true tree:
njdist8 = RF.dist(truetree8,njtree8, rooted=FALSE)
mldist8 = RF.dist(truetree8,mltree8, rooted=FALSE)
bidist8 = RF.dist(truetree8,bitree8, rooted=FALSE)
write.table(njdist8,file=outname,append = T,sep=',',row.names="njdist",col.names=F)
write.table(mldist8,file=outname,append = T,sep=',',row.names="mldist",col.names=F)
write.table(bidist8,file=outname,append = T,sep=',',row.names="bidist",col.names=F)

truetree9 = read.tree(text=quartets[d[n-9-minus,]])
print(quartets[d[n-9-minus,]])
njtree9 = read.tree(file="nj-tree9.txt")
mltree9 = read.tree(file="T39.raxml.bestTree")
bitree9 = read.nexus(file="test9-mb.nexus.con.tre")
## Calculating the Robinson-Foulds distance with true tree:
njdist9 = RF.dist(truetree9,njtree9, rooted=FALSE)
mldist9 = RF.dist(truetree9,mltree9, rooted=FALSE)
bidist9 = RF.dist(truetree9,bitree9, rooted=FALSE)
write.table(njdist9,file=outname,append = T,sep=',',row.names="njdist",col.names=F)
write.table(mldist9,file=outname,append = T,sep=',',row.names="mldist",col.names=F)
write.table(bidist9,file=outname,append = T,sep=',',row.names="bidist",col.names=F)