universe = vanilla
log    =    log/job1-chtc_$(Cluster)_$(Process).log
error  =  error/job1-chtc_$(Cluster)_$(Process).err
output = output/job1_$(Cluster)_$(Process).out

executable = ./RunTrainZou.sh

arguments = trainzou.json  >> test.out &

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files =  TrainZou.py, trainzou.json,  http://proxy.chtc.wisc.edu/SQUID/chtc/python38.tar.gz, Cudapackages.tar.gz, labelsdata.in,  sequencedata.in

+WantGPULab = true
+GPUJobLength = "long"
+wantFlocking = true

request_gpus = 1
request_cpus = 1
request_memory = 128GB
request_disk = 64GB

queue

